language: python
python:
  - "2.7"
# command to install dependencies
services:
  - elasticsearch
  - rabbitmq
  - mongodb
install:
  - pip install -r requirements.txt
  - pip install MySQL-python
  - pip install psycopg2
  - pip install -r requirements_testing.txt
# command to run tests
before_script:
  - mysql -e 'create database writeit;'
  - psql -c 'create database writeit;' -U postgres
script:
  - ./start_local_popit_api.bash
  - coverage run --source=nuntium,contactos,mailit manage.py test nuntium contactos mailit
  - coverage report -m
after_script:
  - coveralls --verbose
env:
  - DB=postgres
  - DB=mysql
  - DB=sqlite3

