language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt --use-mirrors 
# command to run tests
env:
  - DJANGO_VERSION=1.5
script:
  -python manage.py test nuntium contactos
