from messages_test import *
from home_view_test import *
from plugin_architecture import *
from writeitinstances import *
from message_form_test import *
from record_system import *
from send_messages_command import *
from outbound_message import *
from outbound_message_plugin_record import *
from confirmation import *
from answers_test import *